#!/usr/bin/env python3
"""SAST report as a Word document, in the layout of tools/templates/sast-report.docx.

One report per repository scan (a branch or a pull request), by kind of finding, code first:

  1. Code Security   - per rule: severity, status, assignee, risk, recommendation, every
                       occurrence (file, line, status) and the code around it;
  2. Secret Leaks    - every secret: type, file, line, commit, still in code or history only;
  3. Dependencies &  - one row per vulnerable package with its advisories, fixed version and
     Configuration     reachability, plus Trivy configuration checks.

Code findings and review states come from SonarQube (--sonar-url); secrets and dependencies
from the SDT findings.json (--findings), which knows commits, versions and reachability.
Either source alone also works. No text is generated by AI: everything is scanner and rule
data. Stdlib only: the template's styles, numbering and footer are reused.

  SONAR_TOKEN=... python3 tools/sdt_to_docx.py --sonar-url http://localhost:9000 \
      --project-key KEY --branch release/1.0 --findings out/findings.json --src-root source --out report.docx
"""
from __future__ import annotations

import argparse
import base64
import html
import json
import os
import re
import sys
import urllib.parse
import urllib.request
import zipfile
from collections import Counter, OrderedDict
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from xml.sax.saxutils import escape

sys.path.insert(0, str(Path(__file__).resolve().parent))
import sdt_advisory  # noqa: E402  (deterministic advisory; no model needed)

TEMPLATE = Path(__file__).resolve().parent / "templates" / "sast-report.docx"
LOGO = Path(__file__).resolve().parent / "templates" / "logo.png"  # cover and page header; optional, not shipped
SEVERITY_ORDER = ["Critical", "High", "Medium", "Low", "Info"]
SONAR_SEVERITY = {"BLOCKER": "Critical", "CRITICAL": "High", "MAJOR": "Medium", "MINOR": "Low", "INFO": "Info"}
SDT_SEVERITY = {"critical": "Critical", "high": "High", "medium": "Medium", "low": "Low", "info": "Info"}
HOTSPOT_STATUS = {("TO_REVIEW", ""): "To review", ("REVIEWED", "FIXED"): "Fixed",
                  ("REVIEWED", "SAFE"): "Safe", ("REVIEWED", "ACKNOWLEDGED"): "Acknowledged"}
ISSUE_STATUS = {"OPEN": "Open", "CONFIRMED": "Confirmed", "REOPENED": "Open", "ACCEPTED": "Accepted",
                "FALSE_POSITIVE": "False positive", "FIXED": "Fixed", "RESOLVED": "Resolved"}
TEST_PATH = re.compile(r"(^|/)(test|tests|spec|__tests__|integration_test)(/|$)|[._-](test|spec)\.[a-z]+$", re.I)
# Reference-list entries ("OWASP - Top 10 2021 Category A3", "CWE - CWE-79 ...") are citations, not steps.
REFERENCE = re.compile(r"^(OWASP|CWE|MITRE|SANS|NIST|PCI|STIG|CERT|ASVS|MASVS)\b[\s:-]", re.I)
# Link titles from a rule's resources ("Vue.js - Security - Injecting HTML") are not steps either.
DOC_TITLE = re.compile(r"^(?!.*[.!?)]$).{3,100} - .{3,100}$")
SNIPPET_CONTEXT = 3
MAX_EXCERPTS = 20  # kept for compatibility; every finding's code is shown
GROUP_THRESHOLD = 10  # a rule with more findings than this is laid out file by file


# ------------------------------------------------------------------- sonar source
class Sonar:
    def __init__(self, url: str, token: str):
        self.url, self.token = url.rstrip("/"), token

    def get(self, path: str, **params) -> dict:
        query = urllib.parse.urlencode({k: v for k, v in params.items() if v not in (None, "")})
        request = urllib.request.Request(f"{self.url}{path}?{query}")
        request.add_header("Authorization", "Basic " + base64.b64encode(f"{self.token}:".encode()).decode())
        with urllib.request.urlopen(request, timeout=60) as response:
            return json.load(response)

    def paged(self, path: str, key: str, **params) -> list[dict]:
        items, page = [], 1
        while True:
            data = self.get(path, p=page, ps=500, **params)
            items += data.get(key, [])
            total = (data.get("paging") or {}).get("total", data.get("total", 0))
            if page * 500 >= total or not data.get(key):
                return items
            page += 1


def _html_paragraphs(fragment: str, prefer_list: bool = False) -> list[str]:
    """Plain-text paragraphs (or, with prefer_list, list items) from a rule's HTML description.

    Headings and code examples are dropped: they are structure in Sonar's rule page,
    not sentences a reader can act on.
    """
    fragment = re.sub(r"<(h\d|pre)[^>]*>.*?</\1>", " ", fragment or "", flags=re.I | re.S)
    items = re.findall(r"<li[^>]*>(.*?)</li>", fragment, flags=re.I | re.S)
    parts = items if prefer_list and items else re.split(r"</?(?:p|li|ul|ol|div)[^>]*>", fragment, flags=re.I)
    texts = [" ".join(html.unescape(re.sub(r"<[^>]+>", " ", part)).split()) for part in parts]
    return [text for text in texts if len(text) > 2 and not text.endswith(":") and not REFERENCE.match(text)
            and not DOC_TITLE.match(text)]


def rule_texts(rule: dict) -> tuple[list[str], list[str]]:
    """(risk, fixes) from a rule: description sections when Sonar has them, else split on 'How to fix'."""
    sections = {s.get("key"): s.get("content", "") for s in rule.get("descriptionSections") or []}
    if sections:
        risk = _html_paragraphs(sections.get("root_cause", "") or sections.get("introduction", ""))
        fixes = _html_paragraphs(sections.get("how_to_fix", ""), prefer_list=True)
        return risk[:4], fixes[:6]
    desc = rule.get("htmlDesc") or ""
    fix_heading = re.search(r"<h2[^>]*>\s*How to fix it\s*</h2>", desc, re.I)
    head, tail = (desc[:fix_heading.start()], desc[fix_heading.end():]) if fix_heading else (desc, "")
    risk = [p for p in _html_paragraphs(head) if not p.lower().startswith(("standards", "references", "opengrep rule"))]
    fixes = _html_paragraphs(tail.split("<h2")[0], prefer_list=True) if tail else []
    return risk[:4], fixes[:6]


def clean_message(message: str) -> str:
    """One readable line: advisory markdown headings and code ticks removed."""
    text = re.sub(r"#{1,6}\s*(Summary|Description|Details|Impact|Overview)\s*", "", message or "")
    return " ".join(text.replace("`", "").split())


def _path(component_key: str) -> str:
    """'project:lib/a.dart' -> 'lib/a.dart'; a project-level key has no path."""
    return component_key.split(":", 1)[1] if ":" in component_key else ""


# --------------------------------------------------------------------------- model
@dataclass
class Occurrence:
    path: str
    line: int
    message: str
    status: str
    assignee: str
    ai: dict | None = None  # advisory review from sdt_triage_codex.py, never a decision
    link: str = ""  # the finding's page in SonarQube, when it came from there


@dataclass
class Group:
    """One code-security rule and where it fired."""
    rule: str
    name: str
    kind: str  # "Security Hotspot", "Vulnerability" or "Finding"
    severity: str
    risk: list[str] = field(default_factory=list)
    fixes: list[str] = field(default_factory=list)
    occurrences: list[Occurrence] = field(default_factory=list)


@dataclass
class SecretRow:
    kind: str  # gitleaks rule id, e.g. generic-api-key
    path: str
    line: int
    commit: str
    where: str  # "Current code", "Git history only" or "Unknown"
    severity: str
    status: str = "Open"


@dataclass
class DependencyRow:
    package: str
    installed: str
    manifest: str
    fixed: dict = field(default_factory=dict)  # advisory id -> "1.2.3, 2.0.1" (every patched branch)
    advisories: dict = field(default_factory=dict)  # advisory id -> severity
    reachable: str = "Unknown"
    status: str = "Open"

    @property
    def severity(self) -> str:
        return min(self.advisories.values(), key=SEVERITY_ORDER.index) if self.advisories else "Medium"


@dataclass
class ConfigRow:
    check: str
    path: str
    line: int
    message: str
    severity: str
    status: str = "Open"


@dataclass
class Report:
    project: str
    repository: str
    scope: str  # "branch release/1.0" or "pull request 379"
    scope_url: str
    commit: str
    source: str
    code: list[Group]
    secrets: list[SecretRow]
    dependencies: list[DependencyRow]
    config: list[ConfigRow]
    report_date: date
    ai: dict | None = None  # triage.json header: engine, model, calls, stopped
    trend: dict | None = None  # category -> (new, fixed, still open) against the previous scan
    previous: str = ""  # when the previous scan ran
    coverage: list = field(default_factory=list)  # what this scan could not cover
    source_base: str = ""  # https://bitbucket.org/<workspace>/<repo>/src/<commit>: code links point here
    link_to: str = "bitbucket"  # "bitbucket" (default) or "sonar" for file links


# ------------------------------------------------------------------ categorising
# Trivy advisories are dependencies; its other ids (DS-, KSV-, AVD-) are configuration checks.
DEPENDENCY_RULE = re.compile(r"^(external_sdt-trivy[^:]*:sdt-trivy[^-]*(-fs)?-(CVE|GHSA|GO|PYSEC|RUSTSEC|OSV|DSA|RHSA|ELSA)-"
                             r"|sdt:vulnerable-dependency)")
SECRET_RULE = re.compile(r"^(sdt:secret|secrets:|external_sdt-gitleaks)")
CONFIG_RULE = re.compile(r"^external_sdt-trivy")
EXTERNAL_ID = re.compile(r"^external_sdt-[a-z-]+?:sdt-(?:gitleaks|trivy-fs|trivy)-(?P<id>.+)-[0-9a-f]{16}$")
HISTORY_SECRET = re.compile(r"Secret \((?P<kind>[^)]+)\) in git history: (?P<path>[^\s:]+)(?::(?P<line>\d+))?"
                            r"(?: at commit (?P<commit>[0-9a-f]+))?")
DEPENDENCY_MESSAGE = re.compile(r"^(?P<id>\S+) in (?P<package>\S+) (?P<installed>\S+?)(?:: upgrade to (?P<fixed>[^.]+))?\.")


def category(rule_key: str) -> str:
    """'secret', 'dependency', 'config' or 'code' for a Sonar rule key."""
    if SECRET_RULE.search(rule_key):
        return "secret"
    if DEPENDENCY_RULE.search(rule_key):
        return "dependency"
    if CONFIG_RULE.search(rule_key):
        return "config"
    return "code"


def external_id(rule_key: str) -> str:
    """'external_sdt-gitleaks:sdt-gitleaks-gcp-api-key-<hash>' -> 'gcp-api-key'."""
    match = EXTERNAL_ID.match(rule_key)
    return match.group("id") if match else rule_key.split(":", 1)[-1]


def _version(text: str) -> tuple:
    return tuple(int(n) for n in re.findall(r"\d+", text)[:4])


def upgrade_to(row: "DependencyRow") -> str:
    """The lowest version that fixes every advisory of this package, or "" when unknown.

    Each advisory lists one fixed version per maintained branch; the useful one is the
    lowest at or above the installed version. The package needs the highest of those.
    """
    installed, targets = _version(row.installed), []
    for fixed in row.fixed.values():
        candidates = sorted((_version(v), v.strip()) for v in fixed.split(",") if _version(v))
        above = [c for c in candidates if c[0] >= installed] or candidates
        if above:
            targets.append(above[0])
    return max(targets)[1] if targets else ""


def _worse(a: str, b: str) -> str:
    return min(a, b, key=SEVERITY_ORDER.index)


# ------------------------------------------------------------------- sonar source
def from_sonar(sonar: Sonar, project_key: str, branch: str, pull_request: str) -> tuple[str, dict]:
    """Project name and the four categories as SonarQube reports them."""
    scope = {"branch": branch, "pullRequest": pull_request}
    component = sonar.get("/api/components/show", component=project_key, **scope)["component"]
    hotspots = sonar.paged("/api/hotspots/search", "hotspots", projectKey=project_key, **scope)
    issues = sonar.paged("/api/issues/search", "issues", componentKeys=project_key, types="VULNERABILITY",
                         resolved="false", **scope)
    groups: "OrderedDict[str, Group]" = OrderedDict()
    rules: dict[str, dict] = {}
    found = {"code": [], "secret": [], "dependency": [], "config": []}

    def rule(rule_key: str) -> dict:
        if rule_key not in rules:
            rules[rule_key] = sonar.get("/api/rules/show", key=rule_key).get("rule", {})
        return rules[rule_key]

    def code(rule_key: str, kind: str, severity: str, occurrence: Occurrence) -> None:
        if rule_key not in groups:
            risk, fixes = rule_texts(rule(rule_key))
            groups[rule_key] = Group(rule_key, rule(rule_key).get("name", rule_key), kind, severity, risk, fixes)
        group = groups[rule_key]
        group.severity = _worse(group.severity, severity)
        group.occurrences.append(occurrence)

    base = sonar.url
    scope_query = "".join(f"&{k}={urllib.parse.quote(v)}" for k, v in scope.items() if v)

    def link(item: dict, hotspot: bool) -> str:
        if hotspot:
            return f"{base}/security_hotspots?id={urllib.parse.quote(project_key)}{scope_query}&hotspots={item['key']}"
        return f"{base}/project/issues?id={urllib.parse.quote(project_key)}{scope_query}&open={item['key']}"

    entries = [(h["ruleKey"], "Security Hotspot",
                {"HIGH": "High", "MEDIUM": "Medium", "LOW": "Low"}.get(h.get("vulnerabilityProbability"), "Medium"),
                HOTSPOT_STATUS.get((h.get("status", ""), h.get("resolution", "")), h.get("status", "").title()), h)
               for h in hotspots]
    entries += [(i["rule"], "Vulnerability", SONAR_SEVERITY.get(i.get("severity", ""), "Medium"),
                 ISSUE_STATUS.get(i.get("issueStatus") or i.get("status", ""), i.get("status", "").title()), i)
                for i in issues]
    for rule_key, kind, severity, status, item in entries:
        path, line = _path(item.get("component", "")), item.get("line") or 0
        message = clean_message(item.get("message", ""))
        what = category(rule_key)
        if what == "code":
            code(rule_key, kind, severity, Occurrence(path, line, message, status, item.get("assignee", ""),
                                                      link=link(item, kind == "Security Hotspot") if "key" in item else ""))
        elif what == "secret":
            history = HISTORY_SECRET.search(message)
            if history:
                found["secret"].append(SecretRow(history.group("kind"), history.group("path"),
                                                 int(history.group("line") or 0), history.group("commit") or "",
                                                 "Git history only", severity, status))
            else:
                kind_name = external_id(rule_key) if rule_key.startswith("external_") else \
                    ("secret" if rule_key.startswith("sdt:") else rule(rule_key).get("name", rule_key))
                found["secret"].append(SecretRow(kind_name, path, line, "", "Current code", severity, status))
        elif what == "dependency":
            parsed = DEPENDENCY_MESSAGE.match(message)
            if parsed:
                row = DependencyRow(parsed.group("package"), parsed.group("installed"), path)
                row.advisories[parsed.group("id")] = severity
                if parsed.group("fixed"):
                    row.fixed[parsed.group("id")] = parsed.group("fixed").strip()
                row.reachable = "No" if rule_key.endswith("unreachable") else "Yes/unknown"
            else:  # an external per-advisory issue: the package is only in its text
                row = DependencyRow("", "", path)
                row.advisories[external_id(rule_key)] = severity
            row.status = status
            found["dependency"].append(row)
        else:
            found["config"].append(ConfigRow(external_id(rule_key), path, line, message, severity, status))
    found["code"] = list(groups.values())
    return component.get("name", project_key), found


# --------------------------------------------------------------------- sdt source
def from_findings(doc: dict, src_root: Path | None = None) -> dict:
    """The four categories from an SDT findings.json (richer for secrets and dependencies)."""
    groups: "OrderedDict[str, Group]" = OrderedDict()
    secrets, config = [], []
    packages: "OrderedDict[tuple, DependencyRow]" = OrderedDict()
    for f in doc.get("findings", []):
        if f.get("suppression"):
            continue  # covered by an approved exception, e.g. a reviewed false positive
        rule = f.get("rule") or {}
        rule_id = str(rule.get("id") or "unknown")
        adapter = str((f.get("scanner") or {}).get("adapter") or "sdt")
        what = str(f.get("category") or "")
        severity = SDT_SEVERITY.get(str((f.get("severity") or {}).get("canonical", "")).lower(), "Medium")
        location = f.get("location") or {}
        artifact = f.get("artifact") or {}
        path, line = str(location.get("path") or ""), int(location.get("startLine") or 0)
        message = str(f.get("message") or "").split("\n")[0][:300]
        if what == "secret":
            commit = str((f.get("metadata") or {}).get("commit") or "")
            evidence = str((f.get("evidence") or {}).get("text") or "")
            secrets.append(SecretRow(rule_id, path, line, commit[:12], _where(src_root, path, line, evidence), severity))
        elif artifact.get("package"):
            key = (artifact["package"], artifact.get("installedVersion", ""), artifact.get("target", path))
            row = packages.setdefault(key, DependencyRow(*key))
            row.advisories[rule_id] = _worse(row.advisories.get(rule_id, "Info"), severity)
            fixed = artifact.get("fixedVersion") or (f.get("remediation") or {}).get("fixedVersion")
            if fixed:
                row.fixed[rule_id] = str(fixed)
            state = str((f.get("reachability") or {}).get("state") or "")
            row.reachable = {"reachable": "Yes", "unreachable": "No"}.get(state, row.reachable)
        elif what == "misconfiguration" or adapter.startswith("trivy"):
            config.append(ConfigRow(rule_id, path or str(artifact.get("target") or ""), line, message, severity))
        else:
            key = f"{adapter}:{rule_id}"
            if key not in groups:
                guidance = str((f.get("remediation") or {}).get("guidance") or "")
                groups[key] = Group(key, str(rule.get("name") or rule_id), "Finding", severity,
                                    [message] if message else [],
                                    [s.strip() for s in re.split(r"(?<=[.!?])\s+", guidance) if s.strip()])
            group = groups[key]
            group.severity = _worse(group.severity, severity)
            group.occurrences.append(Occurrence(path, line, message, "Not reviewed", ""))
    return {"code": list(groups.values()), "secret": secrets, "dependency": list(packages.values()), "config": config}


PLACEHOLDER = re.compile(r"your|example|change-?me|placeholder|dummy|replace|todo|xxx|\*\*\*|^<|^\$\{|^\{\{|^[\"']{0,2}$",
                         re.IGNORECASE)


def _where(src_root: Path | None, path: str, line: int, evidence: str = "") -> str:
    """Whether a secret is still in the checkout, or only in git history.

    gitleaks scans history, so its line number is where the secret was first committed.
    With the redacted evidence ('key = "[REDACTED]"') the answer is whether that line still
    exists anywhere in the current file with a real-looking value (not a placeholder such as
    "your-api-key"); without it, only whether the line number exists.
    """
    if src_root is None or not path:
        return "Unknown"
    target = src_root / path
    try:
        lines = target.read_text(encoding="utf-8", errors="replace").splitlines() if target.is_file() else []
    except OSError:
        return "Unknown"
    if not lines:
        return "Git history only"
    if "[REDACTED]" in evidence:
        parts = [re.escape(part.strip()) for part in evidence.split("[REDACTED]")]
        pattern = re.compile(r"(\S+)".join(parts))
        # The line may still be there with the secret replaced by a placeholder (an example
        # file cleaned up after the leak): then the secret itself is only in history.
        values = [m.groups() for m in map(pattern.search, lines) if m]
        return "Current code" if any(not all(PLACEHOLDER.search(v) for v in found) for found in values) \
            else "Git history only"
    return "Current code" if 0 < line <= len(lines) else "Git history only"


def merge(sonar: dict, sdt: dict | None) -> dict:
    """Code from SonarQube; secrets, dependencies and configuration from SDT (with Sonar's
    review status where the same file and line match). A secret that both gitleaks and
    Sonar's own secret rules report on one line is listed once."""
    if not sdt:
        merged = dict(sonar)
    else:
        merged = {"code": sonar["code"], "secret": list(sdt["secret"]), "dependency": sdt["dependency"],
                  "config": sdt["config"] or sonar["config"]}
        status = {(r.path, r.line): r.status for r in sonar["secret"]}
        for row in merged["secret"]:
            row.status = status.get((row.path, row.line), row.status)
        merged["secret"] += [r for r in sonar["secret"] if (r.path, r.line) not in {(s.path, s.line) for s in sdt["secret"]}]
    seen, secrets = set(), []
    for row in merged["secret"]:
        key = (row.path, row.line) if row.path else (row.kind, row.commit, id(row))
        if key not in seen:
            seen.add(key)
            secrets.append(row)
    merged["secret"] = sorted(secrets, key=lambda r: (r.where != "Current code", r.path, r.line))
    merged["dependency"] = sorted(merged["dependency"],
                                  key=lambda r: (SEVERITY_ORDER.index(r.severity), r.package, r.installed))
    merged["code"] = sorted(merged["code"], key=lambda g: (SEVERITY_ORDER.index(g.severity), -len(g.occurrences), g.rule))
    return merged


# ------------------------------------------------------------------------ helpers
def snippet(src_root: Path | None, occurrence: Occurrence) -> list[str]:
    """The flagged line with a little context, prefixed with its location, or []."""
    if not src_root or not occurrence.path or occurrence.line < 1:
        return []
    root = src_root.resolve()
    path = (root / occurrence.path).resolve()
    if root not in path.parents or not path.is_file():
        return []
    try:
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError:
        return []
    start, end = max(1, occurrence.line - SNIPPET_CONTEXT), min(len(lines), occurrence.line + SNIPPET_CONTEXT)
    out = [f"// {occurrence.path}:{occurrence.line}"]
    for number in range(start, end + 1):
        marker = ">" if number == occurrence.line else " "
        out.append(f"{marker}{number:>5}  {sdt_advisory.redact(lines[number - 1].rstrip())[:160]}")
    return out


CITED_LINES = re.compile(r"\blines?\s+(\d+)(?:\s*(?:-|–|to|and)\s*(\d+))?", re.I)
MERGE_GAP = 12  # flagged and cited lines this close share one excerpt, so the code reads continuously


def cited_lines(note: dict | None, near: int, reach: int = 200) -> list[int]:
    """Line numbers an advisory cites as evidence ("line 92", "lines 93-106") near the finding."""
    if not note:
        return []
    found = set()
    for key in ("reason", "check", "suggested_fix"):
        for first, last in CITED_LINES.findall(str(note.get(key) or "")):
            a = int(first)
            b = int(last) if last else a
            if b < a or b - a > 20:
                b = a
            found.update(n for n in range(a, b + 1) if abs(n - near) <= reach)
    return sorted(found)


def snippet_blocks(src_root: Path | None, path: str, flagged: list[int], max_block: int = 60,
                   cited: list[int] = ()) -> list[list[str]]:
    """Code excerpts covering every flagged line of one file (marked ">") and every line the
    advisory cites as evidence (marked "*"). Nearby lines share one excerpt, so each shows once.
    Likely secret values are redacted: the report must never carry a credential."""
    if not src_root or not path:
        return []
    root = src_root.resolve()
    target = (root / path).resolve()
    if root not in target.parents or not target.is_file():
        return []
    try:
        lines = target.read_text(encoding="utf-8", errors="replace").splitlines()
    except OSError:
        return []
    hits_all = {n for n in flagged if 1 <= n <= len(lines)}
    cited_all = {n for n in cited if 1 <= n <= len(lines)} - hits_all
    marks = sorted(hits_all | cited_all)
    blocks, windows = [], []
    for n in marks:
        start, end = max(1, n - SNIPPET_CONTEXT), min(len(lines), n + SNIPPET_CONTEXT)
        if windows and start <= windows[-1][1] + MERGE_GAP and end - windows[-1][0] < max_block:
            windows[-1][1] = end
        else:
            windows.append([start, end])
    for start, end in windows:
        hits = [n for n in sorted(hits_all) if start <= n <= end]
        also = [n for n in sorted(cited_all) if start <= n <= end]
        header = f"// {path}:{', '.join(map(str, hits))}" + (f"  (* cited: {', '.join(map(str, also))})" if also else "")
        block = [header]
        for k in range(start, end + 1):
            marker = ">" if k in hits_all else "*" if k in cited_all else " "
            block.append(f"{marker}{k:>5}  {sdt_advisory.redact(lines[k - 1].rstrip())[:160]}")
        blocks.append(block)
    return blocks


def status_summary(occurrences: list[Occurrence]) -> str:
    counts = Counter(o.status for o in occurrences)
    return counts.most_common(1)[0][0] if len(counts) == 1 else ", ".join(f"{s} {n}" for s, n in counts.most_common())


def assignee_summary(occurrences: list[Occurrence]) -> str:
    names = sorted({o.assignee for o in occurrences if o.assignee})
    unassigned = sum(1 for o in occurrences if not o.assignee)
    if not names:
        return "Not assigned"
    return ", ".join(names) + (f" ({unassigned} not assigned)" if unassigned else "")


def plural(n: int, word: str) -> str:
    if n == 1:
        return f"{n} {word}"
    return f"{n} {word[:-1]}ies" if word.endswith("y") and word[-2:-1] not in "aeiou" else f"{n} {word}s"


# ------------------------------------------------------------------ word markup
def run(text: str, bold: bool = False, size: int = 20, color: str = "", mono: bool = False) -> str:
    props = ('<w:rFonts w:ascii="Consolas" w:hAnsi="Consolas"/>' if mono else "") + \
            ("<w:b/>" if bold else '<w:b w:val="0"/>') + (f'<w:color w:val="{color}"/>' if color else "") + \
            f'<w:sz w:val="{size}"/>'
    # Every piece of report text passes here: redact, so no credential can reach a developer's copy.
    return f'<w:r><w:rPr>{props}</w:rPr><w:t xml:space="preserve">{escape(sdt_advisory.redact(text))}</w:t></w:r>'


def para(runs: str, before: int = 40, after: int = 80, align: str = "") -> str:
    # pPr children are schema-ordered: spacing precedes jc.
    jc = f'<w:jc w:val="{align}"/>' if align else ""
    return f'<w:p><w:pPr><w:spacing w:before="{before}" w:after="{after}"/>{jc}</w:pPr>{runs}</w:p>'


def heading(text: str, level: int) -> str:
    return f'<w:p><w:pPr><w:pStyle w:val="Heading{level}"/></w:pPr><w:r><w:t xml:space="preserve">{escape(text)}</w:t></w:r></w:p>'


def label(name: str, value: str) -> str:
    return para(run(f"{name}: ", bold=True) + run(value), before=0, after=80)


def bullet(text: str) -> str:
    return f'<w:p><w:pPr><w:pStyle w:val="ListBullet"/><w:spacing w:after="0"/></w:pPr>{run(text)}</w:p>'


def code_block(lines: list[str]) -> str:
    runs = "".join(f'<w:r><w:rPr><w:rFonts w:ascii="Consolas" w:hAnsi="Consolas"/><w:b w:val="0"/>'
                   f'<w:color w:val="000000"/><w:sz w:val="18"/></w:rPr><w:t xml:space="preserve">{escape(sdt_advisory.redact(line))}</w:t>'
                   + ("<w:br/>" if i < len(lines) - 1 else "") + "</w:r>" for i, line in enumerate(lines))
    return ('<w:p><w:pPr><w:shd w:val="clear" w:color="auto" w:fill="F3F4F6"/><w:spacing w:before="60" w:after="160"/>'
            f'<w:ind w:left="504" w:right="288"/></w:pPr>{runs}</w:p>')


def cell(text: str, width: int, bold: bool = False, fill: str = "", span: int = 1) -> str:
    props = f'<w:tcW w:type="dxa" w:w="{width}"/>' + (f'<w:gridSpan w:val="{span}"/>' if span > 1 else "") + \
            (f'<w:shd w:val="clear" w:color="auto" w:fill="{fill}"/>' if fill else "")
    return f'<w:tc><w:tcPr>{props}</w:tcPr>{para(run(text, bold=bold), before=0, after=80)}</w:tc>'


def table(grid: list[int], rows: list[str]) -> str:
    cols = "".join(f'<w:gridCol w:w="{w}"/>' for w in grid)
    return ('<w:tbl><w:tblPr><w:tblStyle w:val="TableGrid"/><w:tblW w:type="auto" w:w="0"/><w:jc w:val="center"/>'
            '<w:tblLayout w:type="fixed"/><w:tblLook w:firstColumn="1" w:firstRow="1" w:lastColumn="0" w:lastRow="0" '
            f'w:noHBand="0" w:noVBand="1" w:val="04A0"/></w:tblPr><w:tblGrid>{cols}</w:tblGrid>{"".join(rows)}</w:tbl>')


# Fixed wording per review outcome, so every recommendation reads the same way.
REVIEW_OUTCOME = {
    "likely_false_positive": ("False positive - can be marked Safe", "Before marking Safe, confirm",
                              "Record in SonarQube"),
    "likely_true_positive": ("Real issue - fix required", "Confirm impact", "Fix"),
    "needs_context": ("Manual check required", "Check", "Then"),
}
AI_VERDICT_TEXT = REVIEW_OUTCOME  # verdicts this report understands


def apply_triage(groups: list[Group], triage: dict) -> int:
    """Attach advisory AI notes to their occurrences (by rule, file, line); how many matched."""
    notes = {(r.get("rule"), r.get("path"), r.get("line")): r for r in triage.get("results", [])
             if r.get("verdict") in AI_VERDICT_TEXT}
    matched = 0
    for group in groups:
        for occurrence in group.occurrences:
            note = notes.get((group.rule, occurrence.path, occurrence.line))
            if note:
                occurrence.ai = note
                matched += 1
    return matched


def review_lines(note: dict) -> list[tuple[str, str]]:
    """(label, text) rows of one review recommendation, in a fixed order."""
    outcome, check_label, action_label = REVIEW_OUTCOME[note["verdict"]]
    rows = [("Assessment", f"{outcome} (certainty: {str(note.get('confidence', 'low')).title()})")]
    for label_text, key in (("Evidence", "reason"), (check_label, "check"), (action_label, "suggested_fix")):
        if note.get(key):
            rows.append((label_text, note[key]))
    return rows


def ai_line(note: dict) -> str:
    """The same recommendation on one line (for occurrences listed without code)."""
    return "; ".join(f"{name}: {text}" for name, text in review_lines(note))


def consolidate(rows: list[DependencyRow]) -> list[DependencyRow]:
    """One row per (package, version, manifest); advisories without a known package stay separate."""
    merged: "OrderedDict[tuple, DependencyRow]" = OrderedDict()
    for row in rows:
        key = (row.package, row.installed, row.manifest) if row.package else (id(row),)
        if key not in merged:
            merged[key] = row
            continue
        target = merged[key]
        for advisory, severity in row.advisories.items():
            target.advisories[advisory] = _worse(target.advisories.get(advisory, "Info"), severity)
        target.fixed.update(row.fixed)
    return list(merged.values())


# ------------------------------------------------------------------ secret groups
FIREBASE_FILE = re.compile(r"(google-services\.json|GoogleService-Info\.plist|firebase_options\.dart|firebase\.json)$", re.I)
GOOGLE_KEY = re.compile(r"(?i)gcp-api-key|google.?api.?key")


@dataclass
class SecretGroup:
    """All reports of one kind of secret in one file (every build flavour, commit and scanner)."""
    kind: str
    path: str
    count: int = 0
    lines: set = field(default_factory=set)
    commits: set = field(default_factory=set)
    places: set = field(default_factory=set)  # "Current code" / "Git history only"
    statuses: set = field(default_factory=set)
    severity: str = "Info"
    client_key: bool = False  # a Firebase/Google client key: restrict it, do not rotate

    @property
    def where(self) -> str:
        if {"Current code", "Git history only"} <= self.places:
            return "Code and history"
        return next(iter(self.places)) if self.places else "Unknown"

    @property
    def open(self) -> bool:
        return bool(self.statuses & set(OPEN_STATES)) or not self.statuses

    @property
    def action(self) -> str:
        if self.client_key:
            return "Restrict the key (API + Android/iOS app restrictions); rotation not required"
        if "Current code" in self.places:
            return "Rotate, then remove from the code"
        return "Rotate; record the rotation"


def group_secrets(rows: list[SecretRow]) -> list[SecretGroup]:
    """One row per (kind, file): gitleaks history hits, current hits and SonarQube's own reports
    of the same file collapse together; client keys are marked, not treated as leaked secrets."""
    groups: "OrderedDict[tuple, SecretGroup]" = OrderedDict()
    for r in rows:
        kind = "gcp-api-key" if GOOGLE_KEY.search(r.kind) else r.kind
        group = groups.setdefault((kind, r.path), SecretGroup(kind, r.path))
        group.count += 1
        if r.line:
            group.lines.add(r.line)
        if r.commit:
            group.commits.add(r.commit)
        group.places.add(r.where)
        group.statuses.add(r.status)
        group.severity = r.severity if group.count == 1 else _worse(group.severity, r.severity)
        group.client_key = kind == "gcp-api-key" and bool(FIREBASE_FILE.search(r.path or ""))
    return sorted(groups.values(), key=lambda g: (g.client_key, "Current code" not in g.places, g.path, g.kind))


def _short(values: set, limit: int, width: int = 0) -> str:
    items = sorted(values, key=lambda v: (isinstance(v, str), v))
    text = ", ".join(str(v)[:width] if width else str(v) for v in items[:limit])
    return (text + (f" (+{len(items) - limit})" if len(items) > limit else "")) if items else "-"


# ----------------------------------------------------------------------- the text
CATEGORY_TITLES = [("code", "Code Security"), ("secret", "Secret Leaks"),
                   ("dependency", "Dependencies & Configuration (Trivy)")]
OPEN_STATES = ("To review", "Open", "Not reviewed", "Confirmed")
# Reviewer decisions in SonarQube, as the advisory verdict they correspond to.
DECIDED = {"Safe": "likely_false_positive", "False positive": "likely_false_positive", "Fixed": "likely_true_positive",
           "Acknowledged": "likely_true_positive", "Confirmed": "likely_true_positive", "Accepted": "likely_true_positive"}


def _counts(report: Report) -> dict:
    code = [o for g in report.code for o in g.occurrences]
    advisories = sum(len(r.advisories) for r in report.dependencies)
    return {
        "code": (len(code), min((g.severity for g in report.code), key=SEVERITY_ORDER.index, default="None"),
                 sum(1 for o in code if o.status in OPEN_STATES)),
        "secret": (len(report.secrets), min((r.severity for r in report.secrets), key=SEVERITY_ORDER.index, default="None"),
                   sum(1 for g in group_secrets(report.secrets) if g.open)),
        "dependency": (advisories + len(report.config),
                       min([r.severity for r in report.dependencies] + [c.severity for c in report.config],
                           key=SEVERITY_ORDER.index, default="None"),
                       sum(1 for r in report.dependencies if r.status in OPEN_STATES)
                       + sum(1 for c in report.config if c.status in OPEN_STATES)),
    }


def executive_summary(report: Report) -> list[str]:
    code = [o for g in report.code for o in g.occurrences]
    hotspots = sum(len(g.occurrences) for g in report.code if g.kind == "Security Hotspot")
    groups = group_secrets(report.secrets)
    in_code = sum(1 for g in groups if "Current code" in g.places and not g.client_key)
    history = sum(1 for g in groups if g.places == {"Git history only"} and not g.client_key)
    client = sum(1 for g in groups if g.client_key)
    advisories = sum(len(r.advisories) for r in report.dependencies)
    fixable = sum(1 for r in report.dependencies if r.fixed)
    lines = [f"Scope: {report.project}, {report.scope}, scanned with {report.source}."]
    if report.trend:
        new = sum(v[0] for v in report.trend.values())
        fixed = sum(v[1] for v in report.trend.values())
        lines.append(f"Since the previous scan ({report.previous}): {new} new, {fixed} fixed "
                     "(scanner findings; see Changes Since Previous Scan).")
    if code:
        kinds = f" ({plural(hotspots, 'security hotspot')}, {plural(len(code) - hotspots, 'vulnerability')})" \
            if report.source.startswith("SonarQube") else ""
        lines.append(f"Code security: {plural(len(code), 'finding')}{kinds} from "
                     f"{plural(len(report.code), 'rule')} in {plural(len({o.path for o in code if o.path}), 'file')}.")
    else:
        lines.append("Code security: no findings.")
    lines.append(f"Secret leaks: {plural(len(report.secrets), 'report')} in {plural(len(groups), 'place')}"
                 + (f": {in_code} still in the code, {history} only in git history, {client} Firebase/Google client "
                    "keys to restrict rather than rotate" if groups else "") + ".")
    if report.ai:
        reviewed = [o.ai for o in code if o.ai]
        verdicts = Counter(n["verdict"] for n in reviewed)
        lines.append(f"Advisory review of {len(reviewed)} of {len(code)} code findings: "
                     f"{plural(verdicts['likely_false_positive'], 'false positive')} (can be marked Safe after the "
                     f"listed check), {plural(verdicts['likely_true_positive'], 'real issue')} to fix, "
                     f"{verdicts['needs_context']} {'needs' if verdicts['needs_context'] == 1 else 'need'} a manual "
                     "check. Each finding lists what to verify; review states in SonarQube are unchanged.")
        decided = [(o.ai["verdict"], DECIDED[o.status]) for o in code
                   if o.ai and o.status in DECIDED and o.ai["verdict"] != "needs_context"]
        if decided:
            agree = sum(1 for advised, actual in decided if advised == actual)
            lines.append(f"Advisory accuracy so far: it agreed with {agree} of {len(decided)} findings already decided "
                         "in SonarQube.")
    lines.append(f"Dependencies: {plural(advisories, 'advisory')} in {plural(len(report.dependencies), 'package')}"
                 + (f", {fixable} with a fixed version" if report.dependencies else "")
                 + (f"; {plural(len(report.config), 'configuration check')} failed" if report.config else "") + ".")
    return lines


GROUP_GUIDANCE_SECRETS = [
    "Revoke and rotate each credential first: it is already exposed to everyone with repository access.",
    "Deleting the file or rewriting history does not help on its own: existing clones and forks keep the value.",
    "Load secrets at runtime from the CI/CD secret store or a vault; add a pre-commit secret scan.",
    "Client keys that must ship in an app (for example Firebase Android keys) are not secret: restrict them "
    "(API and app restrictions) instead, and record that in SonarQube.",
]
GROUP_GUIDANCE_DEPENDENCIES = [
    "Upgrade each package to the Upgrade To version: the lowest release that fixes all of its listed advisories.",
    "Where no fixed version exists, check the advisory for a workaround and whether the vulnerable function is used.",
    "Packages marked Reachable = No are not imported by any scanned source file: confirm they are not loaded at "
    "runtime before treating them as lower priority.",
]


def recommendations(group: Group) -> list[str]:
    steps = list(group.fixes)
    tests = sum(1 for o in group.occurrences if TEST_PATH.search(o.path or ""))
    if group.kind == "Security Hotspot":
        steps.append("Review each occurrence in SonarQube and set it to Safe, Fixed or Acknowledged with a comment "
                     "that records why, so the decision survives the next scan.")
    if tests:
        steps.append(f"{plural(tests, 'occurrence')} {'is' if tests == 1 else 'are'} in test code; confirm whether "
                     "they are deliberate negative test inputs before treating them as defects.")
    return steps or ["Fix the flagged code, or record in SonarQube why it is not exploitable."]


def review_notes(report: Report) -> list[str]:
    code = [o for g in report.code for o in g.occurrences]
    if not (code or report.secrets or report.dependencies or report.config):
        return ["No open findings in this scope."]
    notes = []
    if code:
        unassigned = sum(1 for o in code if not o.assignee)
        open_code = sum(1 for o in code if o.status in OPEN_STATES)
        notes.append(f"Code security: {open_code} of {len(code)} findings still need a decision"
                     + (f"; {unassigned} are not assigned." if unassigned else "."))
        top = [g for g in report.code if g.severity in ("Critical", "High")]
        if top:
            notes.append("Start with: " + "; ".join(f"{g.name} ({len(g.occurrences)})" for g in top[:3]) + ".")
        tests = sum(1 for o in code if TEST_PATH.search(o.path or ""))
        if tests:
            notes.append(f"{plural(tests, 'code finding')} sit in test code and are candidates for Safe after review.")
    groups = group_secrets(report.secrets)
    in_code = [g for g in groups if "Current code" in g.places and not g.client_key]
    history = [g for g in groups if g.places == {"Git history only"} and not g.client_key]
    client = [g for g in groups if g.client_key]
    if in_code:
        notes.append(f"Secrets still in the current code in {plural(len(in_code), 'place')}: rotate and remove before "
                     "the next release.")
    if history:
        notes.append(f"Secrets only in git history in {plural(len(history), 'place')}: rotate each credential and record "
                     "the rotation.")
    if client:
        notes.append(f"{plural(len(client), 'file')} hold Firebase/Google client keys. They ship inside the app by design: "
                     "restrict them in the Google Cloud console instead of rotating.")
    fixable = [r for r in report.dependencies if r.fixed and r.severity in ("Critical", "High")]
    if fixable:
        notes.append(f"{plural(len(fixable), 'package')} with Critical/High advisories already have a fixed version.")
    return notes


# ------------------------------------------------------------------ layout helpers
ADVISORY_COLOR = "6B21A8"  # purple: the advisory review is visually distinct from scanner facts
BRAND_COLOR = "003F7E"  # navy: headings and table headers
BODY_FONT = "Segoe UI"  # Windows system UI font: modern, installed on every Windows machine
HEADING_FONT = "Segoe UI Semibold"
SEVERITY_FILL = {"Critical": "FECACA", "High": "FED7AA", "Medium": "FEF08A", "Low": "E5E7EB", "Info": "F3F4F6"}
TEXT_WIDTH = 10080  # Letter page, 0.75" margins


class Links:
    """External hyperlinks used in the body; each needs a relationship id in document.xml.rels."""

    def __init__(self):
        self.urls: dict[str, str] = {}

    def rid(self, url: str) -> str:
        if url not in self.urls:
            self.urls[url] = f"rIdLink{len(self.urls) + 1}"
        return self.urls[url]


def bitbucket_base(repository: str, commit: str, host: str = "https://bitbucket.org") -> str:
    """Source browser base for a workspace/repo at a commit, or "" when either is unknown."""
    if "/" not in repository or not commit:
        return ""
    return f"{host.rstrip('/')}/{repository.strip('/')}/src/{commit}"


def code_url(base: str, path: str, lines: list[int], commit: str = "") -> str:
    """A Bitbucket link to a file at the scanned commit (or `commit`), highlighting its line(s)."""
    if not base or not path:
        return ""
    if commit:
        base = base.rsplit("/src/", 1)[0] + f"/src/{commit}"
    marked = sorted({n for n in lines if n})
    anchor = "" if not marked else f"#lines-{marked[0]}" + (f":{marked[-1]}" if marked[-1] != marked[0] else "")
    return f"{base}/{urllib.parse.quote(path)}{anchor}"


def section_heading(text: str, level: int, anchor: str = "", page_break: bool = False) -> str:
    """A heading that stays with what follows, optionally starting a page and carrying a bookmark."""
    ppr = f'<w:pStyle w:val="Heading{level}"/><w:keepNext/><w:keepLines/>' + ("<w:pageBreakBefore/>" if page_break else "")
    title = f'<w:r><w:t xml:space="preserve">{escape(text)}</w:t></w:r>'
    if anchor:
        bookmark_id = abs(hash(anchor)) % 10**8
        title = f'<w:bookmarkStart w:id="{bookmark_id}" w:name="{anchor}"/>{title}<w:bookmarkEnd w:id="{bookmark_id}"/>'
    return f'<w:p><w:pPr>{ppr}</w:pPr>{title}</w:p>'


def internal_link(text: str, anchor: str, indent: int = 0) -> str:
    """A clickable contents entry that jumps to a bookmark."""
    ind = f'<w:ind w:left="{indent}"/>' if indent else ""
    return (f'<w:p><w:pPr><w:spacing w:before="0" w:after="40"/>{ind}</w:pPr><w:hyperlink w:anchor="{anchor}">'
            f'<w:r><w:rPr><w:color w:val="1F4E79"/><w:u w:val="single"/><w:sz w:val="20"/></w:rPr>'
            f'<w:t xml:space="preserve">{escape(text)}</w:t></w:r></w:hyperlink></w:p>')


def link_run(text: str, rid: str, size: int = 20) -> str:
    return (f'<w:hyperlink r:id="{rid}"><w:r><w:rPr><w:color w:val="1F4E79"/><w:u w:val="single"/><w:sz w:val="{size}"/>'
            f'</w:rPr><w:t xml:space="preserve">{escape(text)}</w:t></w:r></w:hyperlink>')


def tcell(content: str, width: int, fill: str = "", span: int = 1, raw: bool = False, bold: bool = False,
          color: str = "") -> str:
    """A table cell; `raw` content is ready-made runs (e.g. a hyperlink)."""
    props = f'<w:tcW w:type="dxa" w:w="{width}"/>' + (f'<w:gridSpan w:val="{span}"/>' if span > 1 else "") + \
            (f'<w:shd w:val="clear" w:color="auto" w:fill="{fill}"/>' if fill else "")
    runs = content if raw else run(str(content), bold=bold, size=18, color=color)
    return f'<w:tc><w:tcPr>{props}</w:tcPr><w:p><w:pPr><w:spacing w:before="0" w:after="40"/></w:pPr>{runs}</w:p></w:tc>'


def trow(cells: str, header: bool = False) -> str:
    """A row that never splits across pages; header rows repeat on every page."""
    return f'<w:tr><w:trPr><w:cantSplit/>{"<w:tblHeader/>" if header else ""}</w:trPr>{cells}</w:tr>'


def data_table(columns: list[tuple[str, int]], rows: list[list], severity_col: int | None = None,
               total: list | None = None, advisory_cols: tuple = ()) -> str:
    """Header row (repeated per page), data rows (severity cells coloured), optional TOTAL row.

    A row value may be a (text, raw_runs) tuple to put a hyperlink in the cell.
    """
    out = [trow("".join(tcell(name, width, fill=BRAND_COLOR, bold=True, color="FFFFFF") for name, width in columns),
                header=True)]
    for row in rows:
        cells = []
        for index, (value, (_, width)) in enumerate(zip(row, columns)):
            if isinstance(value, tuple):
                cells.append(tcell(value[1], width, raw=True))
            else:
                fill = SEVERITY_FILL.get(str(value), "") if index == severity_col else ""
                cells.append(tcell(value, width, fill=fill))
        out.append(trow("".join(cells)))
    if total:
        out.append(trow("".join(tcell(v, w, fill="F3F4F6", bold=True) for v, (_, w) in zip(total, columns))))
    return table([w for _, w in columns], out)


def _advisories(row: DependencyRow, limit: int = 6) -> str:
    ids = sorted(row.advisories, key=lambda a: (SEVERITY_ORDER.index(row.advisories[a]), a))
    return ", ".join(ids[:limit]) + (f" (+{len(ids) - limit} more)" if len(ids) > limit else "")


def advisory_block(note: dict) -> list[str]:
    """The advisory review of one finding, in purple, with fixed labels."""
    rows = review_lines(note)
    out = [para(run("Advisory", bold=True, color=ADVISORY_COLOR), before=0, after=20)]
    for n, (name, text) in enumerate(rows, 1):
        out.append(f'<w:p><w:pPr><w:keepLines/><w:spacing w:before="0" w:after="{120 if n == len(rows) else 20}"/>'
                   f'<w:ind w:left="288"/></w:pPr>{run(name + ": ", bold=True, color=ADVISORY_COLOR)}'
                   f'{run(text)}</w:p>')
    return out


def fix_first(report: Report) -> list[list]:
    """What to do first, in order: confirmed real issues, secrets still in code, other open code
    vulnerabilities, Critical/High packages that have a fix. Each row: priority, what, where, action."""
    rows = []
    for g in report.code:
        for o in g.occurrences:
            if o.ai and o.ai.get("verdict") == "likely_true_positive":
                rows.append(["1", f"{g.name} ({g.rule})", f"{o.path}:{o.line}", o.ai.get("suggested_fix") or "Fix the code"])
    for g in group_secrets(report.secrets):
        if "Current code" in g.places and not g.client_key and g.open:
            rows.append(["2", f"Secret in code: {g.kind}", f"{g.path}:{_short(g.lines, 3)}", g.action])
    for g in report.code:
        if g.kind != "Vulnerability" or g.severity not in ("Critical", "High"):
            continue
        for o in g.occurrences:
            if o.status in OPEN_STATES and not (o.ai and o.ai.get("verdict") in ("likely_true_positive", "likely_false_positive")):
                rows.append(["3", f"{g.name} ({g.rule})", f"{o.path}:{o.line}", "Fix, or mark False positive with a reason"])
    for r in report.dependencies:
        target = upgrade_to(r)
        if target and r.severity in ("Critical", "High"):
            rows.append(["4", f"{r.package} {r.installed} ({r.severity}, {len(r.advisories)} advisories)",
                         r.manifest or "-", f"Upgrade to {target}"])
    return rows


# --------------------------------------------------------------------- the body
def body(report: Report, src_root: Path | None, logo: str = "") -> tuple[str, Links]:
    """document.xml body markup, and the external links it uses. `logo` is a ready picture run."""
    links = Links()
    counts = _counts(report)
    bitbucket = report.link_to != "sonar" and bool(report.source_base)

    def target(occs: list[Occurrence]) -> str:
        """Where a file cell links: Bitbucket source at the scanned commit, else the SonarQube finding."""
        if bitbucket:
            return code_url(report.source_base, occs[0].path, [o.line for o in occs])
        return next((o.link for o in occs if o.link), "")

    link_header = "File (opens Bitbucket)" if bitbucket else "File (opens SonarQube)"
    total = sum(n for n, _, _ in counts.values())
    top = min((sev for _, sev, _ in counts.values() if sev != "None"), key=SEVERITY_ORDER.index, default="None")
    date_text = report.report_date.strftime("%d %B %Y").lstrip("0")

    # ------------------------------------------------ page 1: cover and summary
    parts = [para(logo, before=0, after=200)] if logo else []
    parts.append(para(run("SAST Findings", bold=True, size=32), before=0, after=40))
    if report.scope_url:
        parts.append(f'<w:p><w:pPr><w:spacing w:before="0" w:after="40"/></w:pPr>{link_run(report.scope_url, "rIdScope", 20)}</w:p>')
    parts.append(para(run(f"Security Assessment - {report.source}", bold=True, size=24, color="4B5563"),
                      before=0, after=240))
    meta = [("Project", report.project), ("Repository", report.repository), ("Scope", report.scope),
            ("Commit", report.commit or "-"), ("Scanners", report.source),
            ("Total Findings", f"{total} (code {counts['code'][0]}, secrets {counts['secret'][0]}, "
                               f"dependencies & configuration {counts['dependency'][0]})"),
            ("Needs a Decision", str(sum(n for _, _, n in counts.values()))),
            ("Overall Review Priority", top),
            ("Coverage Gaps", f"{len(report.coverage)} (see Review Notes)" if report.coverage else "None found"),
            ("Report Date", date_text)]
    parts.append(table([3096, 6984], [trow(tcell(k, 3096, fill="E6EEF7", bold=True, color=BRAND_COLOR) + tcell(v, 6984))
                                      for k, v in meta]))
    parts.append(section_heading("Executive Summary", 1, "sec_summary"))
    parts += [para(run(text)) for text in executive_summary(report)]
    parts.append(section_heading("Findings Summary", 1, "sec_findings_summary"))
    rows = [[n, title, counts[key][0], counts[key][1], counts[key][2]] for n, (key, title) in enumerate(CATEGORY_TITLES, 1)]
    parts.append(data_table([("No.", 700), ("Category", 4580), ("Findings", 1600), ("Highest Severity", 1600),
                             ("Needs Decision", 1600)], rows, severity_col=3,
                            total=["", "TOTAL", total, "", sum(n for _, _, n in counts.values())]))

    if report.trend:
        parts.append(section_heading("Changes Since Previous Scan", 1, "sec_trend"))
        parts.append(para(run(f"Compared with the scan of {report.previous}, by scanner finding fingerprint.")))
        parts.append(data_table([("Category", 4680), ("New", 1800), ("Fixed", 1800), ("Still Open", 1800)],
                                [[title, *report.trend.get(key, (0, 0, 0))] for key, title in CATEGORY_TITLES]))

    # ------------------------------------------------ contents: a Word TOC field (page numbers) whose
    # cached result is the clickable list, so it reads correctly before Word updates it.
    parts.append(section_heading("Contents", 1, "sec_contents"))
    parts.append('<w:p><w:r><w:fldChar w:fldCharType="begin" w:dirty="true"/></w:r><w:r><w:instrText xml:space="preserve">'
                 ' TOC \\o "1-2" \\h \\z \\u </w:instrText></w:r><w:r><w:fldChar w:fldCharType="separate"/></w:r></w:p>')
    parts.append(internal_link("Fix First", "sec_fix_first"))
    parts.append(internal_link("1. Code Security", "sec_code"))
    parts += [internal_link(f"1.{n} {g.name} [{rule_ref(g.rule)}] ({len(g.occurrences)})", f"sec_code_{n}", indent=360)
              for n, g in enumerate(report.code, 1)]
    parts.append(internal_link("2. Secret Leaks", "sec_secrets"))
    parts.append(internal_link("3. Dependencies & Configuration (Trivy)", "sec_dependencies"))
    parts.append(internal_link("Review Notes", "sec_notes"))
    parts.append('<w:p><w:r><w:fldChar w:fldCharType="end"/></w:r></w:p>')
    parts.append(para(run("Page numbers appear once Word updates the contents (right-click it, Update Field).",
                          size=16, color="6B7280"), before=0, after=0))

    # ------------------------------------------------ fix first (own page)
    parts.append(section_heading("Fix First", 1, "sec_fix_first", page_break=True))
    todo = fix_first(report)
    if todo:
        parts.append(para(run("Priority 1: confirmed real issues. 2: secrets still in the code. 3: other open "
                              "Critical/High code vulnerabilities. 4: Critical/High packages with a fixed version.")))
        parts.append(data_table([("No.", 600), ("Priority", 900), ("What", 3380), ("Where", 2900), ("Action", 2300)],
                                [[i, *row] for i, row in enumerate(todo[:40], 1)], advisory_cols=(4,)))
        if len(todo) > 40:
            parts.append(para(run(f"{len(todo) - 40} more items follow the same order in the sections below.")))
    else:
        parts.append(para(run("Nothing requires immediate action: no confirmed real issues, no secrets in the current "
                              "code, and no Critical/High packages with a fix. Work through the sections below.")))

    # ------------------------------------------------ 1. code security
    parts.append(section_heading("1. Code Security", 1, "sec_code", page_break=True))
    if not report.code:
        parts.append(para(run("No code security findings in this scope.")))
    else:
        parts.append(data_table([("No.", 700), ("Finding", 3700), ("Rule", 2380), ("Type", 1500), ("Severity", 1000),
                                 ("Count", 800)],
                                [[f"1.{n}", g.name, g.rule, g.kind, g.severity, len(g.occurrences)]
                                 for n, g in enumerate(report.code, 1)], severity_col=4))
    for n, g in enumerate(report.code, 1):
        parts.append(section_heading(f"1.{n} {g.name} [{rule_ref(g.rule)}] - {plural(len(g.occurrences), 'Finding')}",
                                     2, f"sec_code_{n}"))
        parts += [label("Severity", g.severity), label("Rule", g.rule), label("Type", g.kind),
                  label("Status", status_summary(g.occurrences)), label("Assignee", assignee_summary(g.occurrences))]
        if g.risk:
            parts.append(para(run("Risk", bold=True)))
            parts += [para(run(text)) for text in g.risk]
        parts.append(para(run("Recommendation", bold=True)))
        parts += [para(run(f"{i}. ", bold=True) + run(step), before=0, after=0)
                  for i, step in enumerate(recommendations(g), 1)]
        ordered = sorted(g.occurrences, key=lambda o: (o.path or "~", o.line))
        if len(ordered) <= GROUP_THRESHOLD:
            # Few findings: every one gets its own row, code excerpt and advisory.
            parts.append(para(run(f"Occurrences - {plural(len(ordered), 'finding')}", bold=True), before=120))
            rows = []
            for i, o in enumerate(ordered, 1):
                where = o.path or "(project)"
                url = target([o]) if o.path else ""
                rows.append([i, (where, link_run(where, links.rid(url), 18)) if url else where, o.line or "-",
                             o.status, (REVIEW_OUTCOME[o.ai["verdict"]][0].split(" - ")[0] if o.ai else "-")])
            parts.append(data_table([("No.", 600), (link_header if any(target([o]) for o in ordered if o.path) else "File",
                                                    5180), ("Line", 800), ("Status", 1500), ("Advisory", 2000)], rows,
                                    advisory_cols=(4,)))
            for i, occurrence in enumerate(ordered, 1):
                blocks = snippet_blocks(src_root, occurrence.path, [occurrence.line],
                                        cited=cited_lines(occurrence.ai, occurrence.line))
                if blocks:
                    parts.append(para(run(f"#{i} ", bold=True) + run(occurrence.message or g.name), before=160, after=0))
                    parts += [code_block(block) for block in blocks]
                if occurrence.ai:
                    parts += advisory_block(occurrence.ai)
            continue
        # Many findings: grouped by file, one row and one code excerpt per file.
        files: "OrderedDict[str, list[Occurrence]]" = OrderedDict()
        for o in ordered:
            files.setdefault(o.path or "(project)", []).append(o)
        # A rule-based "manual check" says the same thing for every occurrence of a rule: say it once.
        generic = [o for o in ordered if o.ai and o.ai.get("source") == "rules" and o.ai["verdict"] == "needs_context"]
        if generic:
            parts += advisory_block({**generic[0].ai,
                                     "reason": f"Applies to {plural(len(generic), 'occurrence')} of this rule without a "
                                               "more specific assessment below."})
        parts.append(para(run(f"Occurrences - {plural(len(ordered), 'finding')} in {plural(len(files), 'file')}",
                              bold=True), before=120))
        rows = []
        for i, (where, occs) in enumerate(files.items(), 1):
            outcomes = Counter(REVIEW_OUTCOME[o.ai["verdict"]][0].split(" - ")[0] for o in occs if o.ai)
            first_link = target(occs) if occs[0].path else ""
            rows.append([i, (where, link_run(where, links.rid(first_link), 18)) if first_link else where, len(occs),
                         _short({o.line for o in occs if o.line}, 6), status_summary(occs),
                         ", ".join(f"{name} {n}" if len(occs) > 1 else name for name, n in outcomes.most_common()) or "-"])
        parts.append(data_table([("No.", 500), (link_header if bitbucket or any(o.link for o in ordered) else "File", 3880),
                                 ("Hits", 600), ("Lines", 1500), ("Status", 1400), ("Advisory", 2200)], rows,
                                advisory_cols=(5,)))
        # Then every finding, file by file: nothing is hidden, only organised.
        for i, (where, occs) in enumerate(files.items(), 1):
            heading = f"1.{n}.{i} {where} - {plural(len(occs), 'finding')}"
            parts.append(f'<w:p><w:pPr><w:keepNext/><w:spacing w:before="200" w:after="40"/></w:pPr>'
                         f'{run(heading, bold=True)}</w:p>')
            detail = []
            for o in occs:
                note = o.ai or {}
                outcome = REVIEW_OUTCOME[note["verdict"]][0] if note else "-"
                if note.get("source") == "rules" and note.get("verdict") == "needs_context":
                    text = f"{o.message or g.name} - manual check as described for this rule above."
                elif note:
                    text = "; ".join(f"{name}: {value}" for name, value in review_lines(note)[1:])
                else:
                    text = o.message or g.name
                url = target([o]) if o.path else ""
                line_cell = (str(o.line or "-"), link_run(str(o.line or "-"), links.rid(url), 18)) if url \
                    else (o.line or "-")
                detail.append([line_cell, o.status, outcome, text])
            parts.append(data_table([("Line", 800), ("Status", 1300), ("Advisory", 2400), ("Details", 5580)], detail,
                                    advisory_cols=(2, 3)))
            cited = sorted({n for o in occs for n in cited_lines(o.ai, o.line)})
            for block in snippet_blocks(src_root, where, [o.line for o in occs], cited=cited):
                parts.append(code_block(block))

    # ------------------------------------------------ 2. secret leaks
    parts.append(section_heading("2. Secret Leaks", 1, "sec_secrets", page_break=True))
    if not report.secrets:
        parts.append(para(run("No secrets found in the code or its git history.")))
    else:
        groups = group_secrets(report.secrets)

        def secret_cell(g: SecretGroup):
            if not (bitbucket and g.path):
                return g.path or "-"
            # History-only secrets: open the file in the commit where the secret was found.
            commit = sorted(g.commits)[0] if g.places == {"Git history only"} and g.commits else ""
            url = code_url(report.source_base, g.path, sorted(g.lines)[:1], commit)
            return (g.path, link_run(g.path, links.rid(url), 18))

        parts.append(para(run(f"{plural(len(report.secrets), 'report')} from gitleaks and SonarQube, grouped by secret type "
                              f"and file into {plural(len(groups), 'place')}. Values are never printed. Secrets still in "
                              "the code come first; Firebase/Google client keys come last because they are restricted, "
                              "not rotated.")))
        parts.append(data_table([("No.", 500), ("Secret Type", 1500), ("File", 2500), ("Reports", 800), ("Lines", 1200),
                                 ("Commits", 1200), ("Where", 1100), ("Action", 1280)],
                                [[i, g.kind, secret_cell(g), g.count, _short(g.lines, 4), _short(g.commits, 2, 8),
                                  g.where, g.action] for i, g in enumerate(groups, 1)]))
        parts.append(para(run("What to do", bold=True), before=120))
        parts += [para(run(f"{i}. ", bold=True) + run(step), before=0, after=0)
                  for i, step in enumerate(GROUP_GUIDANCE_SECRETS, 1)]

    # ------------------------------------------------ 3. dependencies and configuration
    parts.append(section_heading("3. Dependencies & Configuration (Trivy)", 1, "sec_dependencies", page_break=True))
    parts.append(section_heading("3.1 Vulnerable Packages", 2))
    if not report.dependencies:
        parts.append(para(run("No dependency advisories.")))
    else:
        parts.append(data_table([("No.", 500), ("Package", 1900), ("Installed", 1100), ("Upgrade To", 1300),
                                 ("Advisories", 2480), ("Severity", 900), ("Reachable", 900), ("Manifest", 1000)],
                                [[i, r.package or "(see advisory)", r.installed or "-", upgrade_to(r) or "no fix yet",
                                  _advisories(r), r.severity, r.reachable, r.manifest or "-"]
                                 for i, r in enumerate(report.dependencies, 1)], severity_col=5))
        parts.append(para(run("What to do", bold=True), before=120))
        parts += [para(run(f"{i}. ", bold=True) + run(step), before=0, after=0)
                  for i, step in enumerate(GROUP_GUIDANCE_DEPENDENCIES, 1)]
    if report.config:
        parts.append(section_heading("3.2 Configuration Checks", 2))
        parts.append(data_table([("No.", 600), ("Check", 1300), ("File", 2600), ("Line", 700), ("Severity", 1000),
                                 ("Finding", 3880)],
                                [[i, c.check, c.path or "-", c.line or "-", c.severity, c.message[:200]]
                                 for i, c in enumerate(report.config, 1)], severity_col=4))

    parts.append(section_heading("Review Notes", 1, "sec_notes"))
    parts += [bullet(note) for note in review_notes(report)]
    parts.append(section_heading("Coverage", 2, "sec_coverage"))
    parts += [bullet(gap) for gap in report.coverage] or [para(run("All scanners completed; no coverage gaps were "
                                                                    "reported for this scan."))]
    return "".join(parts), links


# --------------------------------------------------------------- header / footer
def png_size(data: bytes) -> tuple[int, int]:
    """(width, height) in pixels from a PNG header."""
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("logo must be a PNG")
    return int.from_bytes(data[16:20], "big"), int.from_bytes(data[20:24], "big")


def logo_run(rid: str, size: tuple[int, int], width_inches: float, pic_id: int) -> str:
    """An inline picture, width fixed, height by aspect ratio."""
    cx = int(width_inches * 914400)
    cy = int(cx * size[1] / size[0])
    a, pic = "http://schemas.openxmlformats.org/drawingml/2006/main", "http://schemas.openxmlformats.org/drawingml/2006/picture"
    return (f'<w:r><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0"><wp:extent cx="{cx}" cy="{cy}"/>'
            f'<wp:docPr id="{pic_id}" name="Logo {pic_id}"/><wp:cNvGraphicFramePr><a:graphicFrameLocks xmlns:a="{a}" '
            f'noChangeAspect="1"/></wp:cNvGraphicFramePr><a:graphic xmlns:a="{a}"><a:graphicData uri="{pic}">'
            f'<pic:pic xmlns:pic="{pic}"><pic:nvPicPr><pic:cNvPr id="{pic_id}" name="logo.png"/><pic:cNvPicPr/></pic:nvPicPr>'
            f'<pic:blipFill><a:blip r:embed="{rid}"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill>'
            f'<pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="{cx}" cy="{cy}"/></a:xfrm>'
            f'<a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic>'
            f'</wp:inline></w:drawing></w:r>')


HEADER_XML = ('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
              '<w:hdr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
              'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" '
              'xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing">'
              '<w:p><w:pPr><w:pBdr><w:bottom w:val="single" w:sz="4" w:space="4" w:color="D1D5DB"/></w:pBdr>'
              '<w:tabs><w:tab w:val="right" w:pos="10080"/></w:tabs><w:spacing w:before="0" w:after="0"/></w:pPr>'
              '{logo}<w:r><w:rPr><w:b/><w:color w:val="4B5563"/><w:sz w:val="16"/></w:rPr><w:t xml:space="preserve">{left}</w:t></w:r>'
              '<w:r><w:rPr><w:color w:val="6B7280"/><w:sz w:val="16"/></w:rPr><w:tab/><w:t xml:space="preserve">{right}</w:t></w:r>'
              '</w:p></w:hdr>')


def footer_runs(text: str) -> str:
    """Footer text followed by 'Page X of Y' (Word fills in the fields)."""
    small = '<w:rPr><w:b w:val="0"/><w:sz w:val="16"/></w:rPr>'
    return (f'<w:r>{small}<w:t xml:space="preserve">{escape(text)} | Page </w:t></w:r>'
            f'<w:fldSimple w:instr=" PAGE "><w:r>{small}<w:t>1</w:t></w:r></w:fldSimple>'
            f'<w:r>{small}<w:t xml:space="preserve"> of </w:t></w:r>'
            f'<w:fldSimple w:instr=" NUMPAGES "><w:r>{small}<w:t>1</w:t></w:r></w:fldSimple>')


def restyle(styles: str) -> str:
    """Modern typography: Segoe UI everywhere (explicit, so theme fonts cannot override it),
    Semibold for headings, brand navy for heading text."""
    body = f'<w:rFonts w:ascii="{BODY_FONT}" w:hAnsi="{BODY_FONT}" w:eastAsia="{BODY_FONT}" w:cs="{BODY_FONT}"/>'
    styles = re.sub(r"<w:rFonts [^>]*/>", body, styles)

    def heading(match: re.Match) -> str:
        block = match.group(0).replace(body, body.replace(f'"{BODY_FONT}"', f'"{HEADING_FONT}"'))
        return re.sub(r'<w:color w:val="[0-9A-Fa-f]{6}"/>', f'<w:color w:val="{BRAND_COLOR}"/>', block)
    return re.sub(r'<w:style [^>]*w:styleId="Heading[12]".*?</w:style>', heading, styles, flags=re.S)


def retheme(theme: str) -> str:
    """The theme's Latin fonts, so anything that still asks the theme also gets Segoe UI."""
    theme = re.sub(r'(<a:majorFont>\s*<a:latin typeface=")[^"]*', rf"\g<1>{HEADING_FONT}", theme)
    return re.sub(r'(<a:minorFont>\s*<a:latin typeface=")[^"]*', rf"\g<1>{BODY_FONT}", theme)


def write_docx(report: Report, src_root: Path | None, out: Path, template: Path = TEMPLATE,
               logo: Path | None = LOGO) -> None:
    logo_data = logo.read_bytes() if logo and logo.is_file() else b""
    size = png_size(logo_data) if logo_data else None
    markup, links = body(report, src_root, logo_run("rIdLogo", size, 2.2, 101) if size else "")
    date_text = report.report_date.strftime("%d %B %Y").lstrip("0")
    rel_type = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
    rels = [f'<Relationship Id="rIdHeader1" Type="{rel_type}/header" Target="header1.xml"/>']
    if report.scope_url:
        rels.append(f'<Relationship Id="rIdScope" Type="{rel_type}/hyperlink" '
                    f'Target="{escape(report.scope_url, {chr(34): "&quot;"})}" TargetMode="External"/>')
    rels += [f'<Relationship Id="{rid}" Type="{rel_type}/hyperlink" Target="{escape(url, {chr(34): "&quot;"})}" '
             f'TargetMode="External"/>' for url, rid in links.urls.items()]
    if size:
        rels.append(f'<Relationship Id="rIdLogo" Type="{rel_type}/image" Target="media/logo.png"/>')
    header = HEADER_XML.format(logo=(logo_run("rIdHdrLogo", size, 0.9, 102) + '<w:r><w:t xml:space="preserve">  </w:t></w:r>')
                               if size else "", left=escape(f"SAST Report - {report.project}"),
                               right=escape(f"{report.scope} | {date_text}"))
    out.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(template) as src, zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as dst:
        for item in src.infolist():
            data = src.read(item.filename).decode("utf-8") if item.filename.endswith((".xml", ".rels")) else None
            if data is None:
                dst.writestr(item, src.read(item.filename))
                continue
            if item.filename == "word/document.xml":
                data = data.replace("<!--BODY-->", markup)
                # Page header on every page but the cover; the cover has no header or footer.
                data = re.sub(r"(<w:sectPr[^>]*>)", r'\1<w:headerReference w:type="default" r:id="rIdHeader1"/>', data, 1)
                data = data.replace("<w:docGrid", "<w:titlePg/><w:docGrid", 1)
            elif item.filename == "word/footer1.xml":
                data = re.sub(r"<w:r>(?:(?!<w:r>).)*?<!--FOOTER-->.*?</w:r>", lambda m: footer_runs(f"SAST Report - {report.project} | {date_text}"),
                              data, count=1, flags=re.S)
            elif item.filename == "word/_rels/document.xml.rels":
                data = data.replace("<!--RELS-->", "".join(rels))
            elif item.filename == "word/styles.xml":
                data = restyle(data)
            elif item.filename == "word/theme/theme1.xml":
                data = retheme(data)
            elif item.filename == "[Content_Types].xml":
                data = data.replace("</Types>", '<Override PartName="/word/header1.xml" ContentType='
                                                '"application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml"/></Types>')
                if size and 'Extension="png"' not in data:
                    data = data.replace("<Default ", '<Default Extension="png" ContentType="image/png"/><Default ', 1)
            dst.writestr(item, data)
        dst.writestr("word/header1.xml", header)
        if size:
            dst.writestr("word/media/logo.png", logo_data)
            dst.writestr("word/_rels/header1.xml.rels",
                         '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns='
                         '"http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rIdHdrLogo" '
                         f'Type="{rel_type}/image" Target="media/logo.png"/></Relationships>')


# ---------------------------------------------------------------- trend / coverage
def _category_of(finding: dict) -> str:
    kind = str(finding.get("category") or "")
    if kind == "secret":
        return "secret"
    if (finding.get("artifact") or {}).get("package") or kind == "misconfiguration":
        return "dependency"
    return "code"


def rule_ref(rule: str) -> str:
    """A short name for a rule that is the same in every report, unlike its section number."""
    return rule.rsplit(":", 1)[-1].rsplit(".", 1)[-1] or rule


def compare(current: dict, previous: dict) -> dict:
    """category -> (new, fixed, still open), by SDT finding fingerprint.

    A finding an exception covers in the current scan is none of the three: it was not
    fixed, and it is no longer open, so it is left out of both sides.
    """
    excepted = {(f.get("fingerprint") or {}).get("value") for f in current.get("findings", []) if f.get("suppression")}

    def index(doc):
        out = {"code": set(), "secret": set(), "dependency": set()}
        for f in doc.get("findings", []):
            value = (f.get("fingerprint") or {}).get("value")
            if value and value not in excepted:
                out[_category_of(f)].add(value)
        return out
    now, before = index(current), index(previous)
    return {k: (len(now[k] - before[k]), len(before[k] - now[k]), len(now[k] & before[k])) for k in now}


def coverage_gaps(coverage: Path | None, findings: Path | None) -> list[str]:
    """Gaps the pipeline reported, plus scanners the run manifest says did not complete."""
    gaps = []
    if coverage and coverage.is_file():
        gaps += [line.strip() for line in coverage.read_text().splitlines() if line.strip()]
    manifest = findings.parent / "run-manifest.json" if findings else None
    if manifest and manifest.is_file():
        try:
            for task in json.loads(manifest.read_text()).get("tasks") or []:
                state = str(task.get("state") or "")
                if task.get("adapter") and state and state != "completed":
                    gaps.append(f"Scanner {task['adapter']} did not complete ({state}): its findings may be missing.")
        except ValueError:
            pass
    return gaps


# --------------------------------------------------------------------------- main
def main() -> int:
    ap = argparse.ArgumentParser(description="SAST report (.docx) from SonarQube and/or an SDT findings.json.")
    ap.add_argument("--out", type=Path, default=Path("sast-report.docx"))
    ap.add_argument("--sonar-url", help="read code findings and review states from SonarQube (token in SONAR_TOKEN)")
    ap.add_argument("--project-key")
    ap.add_argument("--branch", default="")
    ap.add_argument("--pull-request", default="")
    ap.add_argument("--findings", type=Path,
                    help="SDT findings.json: secrets and dependencies come from it (with --sonar-url), or everything")
    ap.add_argument("--src-root", type=Path, help="checkout to quote code excerpts from")
    ap.add_argument("--repository", default="", help="e.g. workspace/repo")
    ap.add_argument("--scope-url", default="", help="link to the branch or pull request")
    ap.add_argument("--commit", default="")
    ap.add_argument("--project-name", default="")
    ap.add_argument("--template", type=Path, default=TEMPLATE)
    ap.add_argument("--logo", type=Path, default=LOGO, help="PNG for the cover and page header (default: templates/logo.png when present; none is shipped)")
    ap.add_argument("--triage", type=Path, help="per-finding review recommendations from sdt_triage_codex.py (optional)")
    ap.add_argument("--previous-findings", type=Path, help="findings.json of the previous scan of this branch (trend)")
    ap.add_argument("--coverage", type=Path, help="text file, one coverage gap per line (e.g. lint skipped)")
    ap.add_argument("--link-to", choices=("bitbucket", "sonar"), default="bitbucket",
                    help="where file links point: Bitbucket source at the scanned commit (default) or SonarQube")
    ap.add_argument("--source-url", default="",
                    help="source browser base, e.g. https://bitbucket.org/ws/repo/src/<commit> "
                         "(default: derived from --repository and --commit on bitbucket.org)")
    ap.add_argument("--group-threshold", type=int, default=GROUP_THRESHOLD,
                    help="rules with more findings than this are laid out file by file (default 10)")
    args = ap.parse_args()
    globals()["GROUP_THRESHOLD"] = args.group_threshold
    if not (args.sonar_url or args.findings):
        print("sdt_to_docx: give --sonar-url and/or --findings", file=sys.stderr)
        return 2

    sdt = None
    if args.findings:
        try:
            sdt = from_findings(json.loads(args.findings.read_text()), args.src_root)
        except (OSError, ValueError) as exc:
            print(f"sdt_to_docx: invalid findings: {exc}", file=sys.stderr)
            return 2
    if args.sonar_url:
        token = os.environ.get("SONAR_TOKEN", "")
        if not (token and args.project_key):
            print("sdt_to_docx: --sonar-url needs --project-key and SONAR_TOKEN", file=sys.stderr)
            return 2
        try:
            name, sonar = from_sonar(Sonar(args.sonar_url, token), args.project_key, args.branch, args.pull_request)
        except (OSError, ValueError, KeyError) as exc:
            print(f"sdt_to_docx: cannot read SonarQube: {exc}", file=sys.stderr)
            return 2
        source = "SonarQube + OpenGrep + Gitleaks + Trivy" if sdt else "SonarQube"
        found = merge(sonar, sdt)
    else:
        name, source = args.project_name or args.repository or "project", "OpenGrep + Gitleaks + Trivy"
        found = merge(sdt, None)
    found["dependency"] = consolidate(found["dependency"])

    scope = f"pull request {args.pull_request}" if args.pull_request else f"branch {args.branch or 'main'}"
    project = args.project_name or name.split("/")[-1]
    ai = None
    if args.triage and args.triage.is_file():
        try:
            triage = json.loads(args.triage.read_text())
            if apply_triage(found["code"], triage):
                ai = {k: triage.get(k) for k in ("engine", "model", "calls", "failed_calls", "stopped")}
        except ValueError:
            print("sdt_to_docx: triage file unreadable; report without AI notes", file=sys.stderr)
    # Every code finding gets an advisory: the model's where it ran, the deterministic rules otherwise.
    for group in found["code"]:
        for occurrence in group.occurrences:
            if not occurrence.ai:
                occurrence.ai = sdt_advisory.assess(group.rule, occurrence.path, occurrence.line, args.src_root)
    ai = ai or {"engine": "rules"}
    trend, previous = None, ""
    if args.previous_findings and args.previous_findings.is_file() and args.findings:
        try:
            before = json.loads(args.previous_findings.read_text())
            trend = compare(json.loads(args.findings.read_text()), before)
            previous = str(before.get("generatedAt") or "")[:10] or "the previous run"
        except (OSError, ValueError):
            trend = None
    report = Report(project, args.repository or name, scope, args.scope_url, args.commit, source,
                    found["code"], found["secret"], found["dependency"], found["config"], date.today(), ai,
                    trend, previous, coverage_gaps(args.coverage, args.findings),
                    args.source_url or bitbucket_base(args.repository, args.commit), args.link_to)
    write_docx(report, args.src_root, args.out, args.template, args.logo)
    code = sum(len(g.occurrences) for g in report.code)
    print(f"sdt_to_docx: wrote {args.out} (code {code} in {len(report.code)} rules, secrets {len(report.secrets)}, "
          f"packages {len(report.dependencies)}, configuration {len(report.config)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
